# Generated by Django 4.0.6 on 2024-06-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=9)),
                ('level', models.IntegerField(choices=[(9, 'Nine'), (16, 'Sixteen'), (24, 'Twenty Four'), (0, 'Custom')], default=9)),
                ('completed', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bomb_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('state', models.IntegerField(choices=[(-1, 'Bomb'), (0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')], default=None, null=True)),
                ('is_revealed', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.board')),
            ],
        ),
    ]
