# Generated by Django 4.0.6 on 2024-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='success',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
