# Generated by Django 4.0.6 on 2024-06-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_cell_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
